{application,teller,
             [{description,"TAGP Project"},
              {vsn,"1.0.0"},
              {modules,[index_dtl,over_dtl,over_handler,reset_handler,
                        statistiek_dtl,statistiek_handler,tagp,tagp_app,
                        tagp_handler]},
              {registered,[tagp]},
              {applications,[kernel,stdlib,cowboy,erlydtl,runtime_tools,wx,
                             observer]},
              {mod,{tagp_app,[]}},
              {env,[]}]}.
